version : '3'
services:
  proxy:
    image: nginx:1.19.5-alpine
    restart: always
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    ports:
      - "80:80"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
