# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"

gem "jekyll", "4.2.2"
gem 'jekyll-environment-variables'
group :jekyll_plugins do
  gem "jekyll-feed"
  gem "jekyll-seo-tag"
  gem "jekyll-sitemap"
  gem "jekyll-paginate"
  gem "datatables"
end

